### ISSUE TITLE
Review of MVP and fixes

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-jkan#13]
More comments from my test uploading datasets. Most are small fixes.

**Schema options and descriptions**

- [x] Edit button allows to only edit contribute (dataset) table and resources; not specific schemas
- [x] "Trigger" hazard and process choices can be empty > they are not required but field does not have empty selection
- [x] Add "N/A" to Frequency options for historical events and extent datasets. Also note frequency value didn't save correctly (already fixed in md file):
```
    frequency_type:
      - Rate
``` 
- [x] "Additional information about this specific event" > "Additional information about the event"
- [x] "Level of data representation" > "Data representation"
	- Footprints
	- Grid
	- Administrative unit
- [x] Hazard type, hazard process, and Intensity measure in display page should show label instead of code
- [x] still getting access denied on newly added downloads
- [x] conflict on "category" attribute, see this [one](https://github.com/GFDRR/rdl-jkan/edit/gh-pages/_datasets/afg-loss-fl.md)
```
category:
  - Loss
  - Indicators
```
- [x] loss schema to use [component]_link as links; link name from target title?

**General and cosmetic stuff**

- [x] rename login link as "Admin login"
- [x] "Purpose" as large (or enlargeable) form field - will include long paragraphs
- [x] Link to biblio resource embedded in biblio title instead of plain url display
- [x] Geographic coverage does not display in the dataset page
- [x] Invert abstract with notes (abstract field containing description shown below title and in list summary. Notes for extra info.)
- [ ] Force field description width (when purpose field gets big, label colunn shrinks too much)
- [x] Mail to maintainer contact embedded as "mailto" on maintainer name. Possible to hide address to bots?
- [x] Additional field to specify name of metadata file stored (shorter than title e.g. hzd-afg-fl)
- [x] Would be possible to have [hint of fields content](https://material.angular.io/components/form-field/overview) in grey? I guess so from "abstract" field. Then: 
    - "Bibliographic resource (author; title; year)" > Bibliographic resource; hint:  author (year) - title
    - "Reference coordinate system"; Hint: 4326 (WGS84)
    - "Probability of occurrence"; Hint: RP  list (10, 100, 1000 years) or range (10-1000 years)

**Under discussion: add creator field** to contribution
As suggested in the exchange with Giuseppe, we should have maintainer and creator (and relative contact email) as separate entities.
That would also bring us one attribute closer to dublincore standard: 1) creator, 2) publisher and 3) contributor (mainteiner).
@stufraser1 to confirm.

**Comment by ConnectedSystems** [comment]
> "Would be possible to have hint of fields content in grey?"

Yes, but so far only for text fields.

You add a "placeholder" field for each item in rdl.yml

> "Force field description width (when purpose field gets big, label colunn shrinks too much)"

Suggest we get someone with more experience with bootstrap/responsive design to do this

**Comment by matamadio** [comment]
Great job; all working as expected.
Some minor improvement:

- [x] Hide filename attribute from dataset page view
- [x] Format filter does not return expected number of results (e.g. 5 gpkg in the filter, 1 is shown)
- [x] enum lists with spaces gets cropped to first word only. E.g. "Return period" is saved as "Return" and exposed asset category "Crops, livestock and forest" is saved as "Crops," (fixed manually in datasets)
- [x] Schema component attribute prefereably show as first attribute in RDL Schema Info (would be cooler to have a symbol showing near title instead; also to use color code. But we don't have graphics yet so just a thought)
- [ ] may need to allow more fields to include multiple values, but not confirmed yet; is it hard?

**Comment by ConnectedSystems** [comment]
"may need to allow more fields to include multiple values, but not confirmed yet; is it hard?"

Depending on the field. It largely is doable but can have implications/complications which require changes to be made all over the code base.

As for the Schema component display position I will leave that til next week as it is fairly low priority

**Comment by matamadio** [comment]
Because many packages are together in a page, I think is useful to:

- [x] add an additional "description" field for each resource, to show as first field on details.

**Comment by ConnectedSystems** [comment]
The following outstanding items will be addressed at a later date:

- may need to allow more fields to include multiple values, but not confirmed yet
  [to be confirmed]
- Force field description width (when purpose field gets big, label colunm shrinks too much)
  [to be conducted with designer, considering responsive design principles]

These can be raised again in a future issue so I am closing this one.

**Comment by matamadio** [comment]
After conversation with Stu:

- [x] Dataset page to hide some attributes: occurrence_start, occurrence_end, occurrence_span.
These are still part of the md file, but they should be hidden from the website page.

Reopening thread for the purpose of team review.

**Comment by matamadio** [comment]
- [x] Some datasets' abstract don't catch in the dataset list. I thought it was because of special char "/" and I removed it from text, but still missing.

![immagine](https://user-images.githubusercontent.com/44863827/111470223-e9bec500-8727-11eb-8ae6-f3e77e939d9b.png)
![immagine](https://user-images.githubusercontent.com/44863827/111470265-f6431d80-8727-11eb-8413-c32354089546.png)

**Comment by matamadio** [comment]
Couple of bugs:

- [ ] Hazard_type is added twice when adding / editing a dataset.
- [ ] Hazard trigger shows hazard_type instead
- [ ] The "notes" field is automatically filled with "description" > maybe this was a workaround to show "description" instead of "notes" in layer list?
