### ISSUE TITLE
Improving connection between same-project datasets

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-jkan#16]
support explicit linking, via project ID fields in all schema > enables linking independent of loss data (enable link across exp, hazard only for example). Current linkage occurs in loss dataset only

**Comment by matamadio** [comment]
Not a priority but something to consider for enhancing the interconnectivity of data, especially according to new agreed framing of datasets (DCAT compliant) where we split different sources in different dataset pages. Then it woulbe be helpful to have a box in the page with links to related datasets:

- Dataset page: population exposure for country
  - Dataset metadata (general and specific)
  - Box with links to other pages:
    - exposure sets for same country (e.g. buildings, or GDP)
    - hazard datasets covering the country
    - risk results
