### ISSUE TITLE
JKAN UI changes for RDL

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-jkan#7]
- [x] Download md file from page via button
- [x] License to display name of license as a link to url in both dataset list and detail page.
- [x] ISO3 geo code should show name of country
- [x] Filter by country name
- [x] Filter by available file type
- [x] Footer for legal, privacy, etc links + logos (?)
- [x] Support multiple choices for ISO3 and other attributes
- [x] Fancy "add dataset" pseudo-dynamic form (changes with component)
- [x] Common enums formalised as common dropdown menus (code stored, name shown)
- [x] Minimal error checking on form submission (required fields; errors)

**Comment by ConnectedSystems** [comment]
@matamadio 

Regarding license display as link, I've written some code so this information is displayed as we want.

JKAN matches a provided URL with one defined in the [licenses.yml file](https://github.com/GFDRR/rdl-jkan/blob/gh-pages/_data/licenses.yml).

Please note that dataset entries should now define the link (as defined in the above file), not the license name as plain text.
See "License" field [here](https://raw.githubusercontent.com/GFDRR/rdl-jkan/gh-pages/_datasets/afg-haz-fl-kabul.md) as an example

**Comment by matamadio** [comment]
Any comment on the jkan landing page?
Do we want the header link to open directly the dataset list instead?

**Comment by matamadio** [comment]
Submit dataset requires login enabled to work properly.
The "Add dataset" button is hidden if not logged.
Login is restricted to repo members (added manually).

**Comment by ConnectedSystems** [comment]
Added tentative legal disclaimer page using TH! text as an initial template: @stufraser1 and @pzwsk to review and adjust when able.

http://jkan.riskdatalibrary.org/legal/

**Comment by matamadio** [comment]
More comments from my test uploading datasets. Most are small fixes.

**Schema options and descriptions**

- [ ] Invert abstract with notes (abstract field containing description shown below title and in list summary. Notes for extra info.)
- [ ] "Trigger" hazard and process choices can be empty (not required)
- [ ] Add "N/A" to Frequency options for historical events and extent datasets
- [ ] "Additional information about this specific event" > "Additional information about the event"
- [ ] "Level of data representation" > "Data representation"
	- Footprints
	- Grid
	- Administrative unit
- [ ] Geographic coverage does not displaying in the dataset page
- [ ] Would be possible to have [hint of fields content](https://material.angular.io/components/form-field/overview) in grey? 
    - "Bibliographic resource (author; title; year)" > Bibliographic resource (hint:  author (year) - title)
    - "Reference coordinate system" (Hint: 4326 [WGS84])
- [ ] - still getting access denied on download


**General and cosmetic stuff**

- [ ] rename login as "Admin login"
- [ ] "Purpose" as large (or enlargeable) form field - will include long paragraphs
- [ ] Force field description width (when purpose field gets big, label colunn shrinks too much)
- [ ] Link to biblio resource embedded in biblio title instead of plain url display
- [ ] Mail to maintainer contact embedded as "mailto" on maintainer name. Possible to hide address to bots?


**For discussion: add creator field**
As suggested in the exchange with Giuseppe, we should have maintainer and creator (and relative contacts) as separate entities.

**Comment by ConnectedSystems** [comment]
Closing this issue as an acceptable level of completion has been reached.

Will concentrate further efforts on the requested changes here: https://github.com/GFDRR/rdl-jkan/issues/13
