### ISSUE TITLE
Add footer with GFDRR logo

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/rdl-jkan#9]

**Comment by matamadio** [comment]
Transparent png logo here: https://github.com/GFDRR/rdl-jkan/tree/rdl-0.1/img/logos/

**Comment by matamadio** [comment]
Links to website pages are broken

**Comment by pzwsk** [comment]
Hi Mattia, let me have a look. 

Also, pages are only on dev version for now.

**Comment by matamadio** [comment]
Are we going to keep dev.riskdatalibrary or use the base address at some point?
Internal links and other things need to be edited accordingly @ConnectedSystems

**Comment by pzwsk** [comment]
dev.riskdatalibrary.org is only a development version so you should not link anything to it.

Also, I added you on the repo so that you can review
https://github.com/GFDRR/rdl-website/issues/103

Thanks

**Comment by matamadio** [comment]
Footer is added, could be improved by designer (spacing, colors etc)
